rollNum=int(input("enter roll num"))
name=input("enter name")
s1=int(input("enter sun b marks"))
s2=int(input("enter sun b marks"))
s3=int(input("enter sun b marks"))
total=s1+s2+s3
div=total/300
per=div*100
print("total=",total)
print("div=",div)
print("per=",per)
